### ISSUE TITLE
 Create a Sphinx theme based on the FOSSASIA theme 

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/sphinx_fossasia_theme#3]
This repository was created following discussion in https://github.com/fossasia/yaydoc/issues/2 and in the public [gitter channel](https://gitter.im/fossasia/yaydoc) of [yaydoc](https://github.com/fossasia/yaydoc). It was decided that a separate repository will exist (in contrast to a subdirectory that existed in Yaydoc's repository) FOSSASIA's project.

This issue will exist as a parent issue with various updates to the theme as its children.

- [ ] ~Add a base templating HTML structure https://github.com/fossasia/sphinx_fossasia_theme/issues/4~
- [x]  Integrate a protype bootstrap layout for the theme https://github.com/fossasia/sphinx_fossasia_theme/issues/5
- [x] Update theme with Header and Footer #8 
- [x] Update the theme adding Left sidebar with Smooth Scrolling  #9

**Comment by vijay938** [comment]
I want to work on this issue
